### PR TITLE
Renaming (updated)

### PR DESCRIPTION
**Pull request by Alexle1709**

### CODE REVIEW

**Comment by gboehl** [comment]
Much better, thanks! But some models still contain the simulated restults (like `f_simul.m`) and similar. Could you please remove them as well?

**Comment by gboehl** [comment]
We are currently looking for a way to exclude these files from commits automatically. In the meanwhile you will have to remove them manually...

**Comment by Alexle1709** [comment]
I'm not sure how it can happen because i find nothing like that in my local folder, but it appears in Github (NK-GK11 for example). I tried to delete it directly from Github but I can't, only Jan can do it. Please check it again. Thanks.

**Comment by Alexle1709** [comment]
> 
> 
> Much better, thanks! But some models still contain the simulated restults (like `f_simul.m`) and similar. Could you please remove them as well?

I'm not sure how it can happen because i find nothing like that in my local folder, but it appears in Github (NK-GK11 for example). I tried to delete it directly from Github but I can't, only Jan can do it. Please check it again. Thanks.

**Comment by j2L4e** [comment]
> We are currently looking for a way to exclude these files from commits automatically.

Actually there's no need to do so if you don't add these files in the first place. They're not automatically added to git just because they exist, you have to deliberately add them.
So don't just `git add *` but please just add the files you actually want in git.

**Comment by AlexDece** [comment]
I also have some files modified, which I don't want to upload.
After adding the files you want to upload, the unwanted files should still be red instead of green (when using "git status").
Then don't use
"git commit -a -m'commit message' "
because this will commit all green AND red files, so also the unwanted files.
Instead use 
"git commit -m'commit message' "
because this will commit green files only. Then there shouldn't occur the problem mentioned above.

Hope this helps.

**Comment by Alexle1709** [comment]
I will make the new pull request to see if those files appear again

**Pull request closed without merging**
