### PR TITLE
[electron7] migrate dialogs from callbacks to promises

### LINKED ISSUE #70: Failed to launch the MMB interface
Hi Jan and Gregor, 

The MMB interface is failed to launch on my MacBook, with four blue circles shining as you can see in the attached screenshots. The problem remains even after I re-forked and re-cloned everything under the master branch.
Screen Shot 2019-11-22 at 2 59 12 PM

I also attached the terminal report and the console report below for your reference.
Screen Shot 2019-11-22 at 3 10 50 PM
[Report.txt](https://github.com/IMFS-MMB/mmb-gui-electron/files/3879848/Report.txt)

Thanks for the help!

Best,
Jin

### PR DESCRIPTION
**Pull request by j2L4e**
fixes #70

### CODE REVIEW

**Comment by cch388** [comment]
Hi Jan, 

Another error occurred unfortunately. After I ticked two models (NK_AFL15 and NK_BGEU10), one policy rule (Taylor), one shock (Monetary Policy Shock) and one variable (Inflation), I got an error that says "Undefined function 'fsolve' for input arguments of type 'function_handle'." Please see attached screenshots. Thanks.
Screen Shot 2019-11-25 at 1 11 37 PM
Screen Shot 2019-11-25 at 1 11 59 PM

**Comment by cch388** [comment]
To illustrate further, I pressed "Compare" and the interface was running and gave this message, instead of some impulse response.

**Comment by j2L4e** [comment]
Thanks for the details!
That's an error in the model. I've pushed a new version to master that indicates where the error happened in the script. It doesn't seem to happen in octave by the way. It'd be best if you filed a separate issue so someone else can take care of this

**Comment by cch388** [comment]
Ah, I see. So it was my bad luck that I chose a model that has some errors in it. Yeah, I tried other models and got some impulse response. Thanks, I will report errors in the two models in Issue.

**Pull request merged**
